version: '3'
services:
    calculator:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        container_name: calculator-server
        ports:
            - "8080:8080"
            - "8000:8000"
